print ("2013 Random Generators 0.1.00")
print (">>>")
import random
input ("With Random Generator, you can generate random. Press enter to continue.")
print ( )
print ("Here is a random number.")
print (random.randint(0, 1999999))
print ( )
input ("Press enter to continue.")
print ( )
print ("Here is a string of random characters.")
print (random.random())
print ( )
input ("Press enter to close Random Generator.")